import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { colors } from '../src/theme/colors';
import { vetColors } from '../src/theme/vetColors';
import { spacing } from '../src/theme/spacing';
import { typography } from '../src/theme/typography';
import { borderRadius } from '../src/theme/borderRadius';
import { elevation } from '../src/theme/elevation';
import { duration } from '../src/theme/animation';

function toKebabCase(str: string): string {
  return str
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1-$2')
    .toLowerCase();
}

function generateCssTokens(): string {
  const lines: string[] = [];

  lines.push('/* Auto-generated by @breeyo/ui — do not edit manually */');
  lines.push(':root {');

  // Colors
  lines.push('  /* Colors */');
  for (const [key, value] of Object.entries(colors)) {
    lines.push(`  --color-${toKebabCase(key)}: ${value};`);
  }

  lines.push('');

  // Vet identity (D-23)
  lines.push('  /* Vet identity (D-23) */');
  vetColors.forEach((hex, i) => lines.push(`  --vet-hue-${i + 1}: ${hex};`));

  lines.push('');

  // Spacing
  lines.push('  /* Spacing */');
  for (const [key, value] of Object.entries(spacing)) {
    lines.push(`  --spacing-${key}: ${value}px;`);
  }

  lines.push('');

  // Typography
  lines.push('  /* Typography */');
  lines.push("  --font-family: 'Inter', system-ui, sans-serif;");
  for (const [key, value] of Object.entries(typography)) {
    const kebab = toKebabCase(key);
    lines.push(`  --font-size-${kebab}: ${value.fontSize}px;`);
    lines.push(`  --line-height-${kebab}: ${value.lineHeight}px;`);
    lines.push(`  --font-weight-${kebab}: ${value.fontWeight};`);
    if ('letterSpacing' in value) {
      lines.push(
        `  --letter-spacing-${kebab}: ${(value as { letterSpacing: number }).letterSpacing}px;`,
      );
    }
  }

  lines.push('');

  // Border radius
  lines.push('  /* Border Radius */');
  for (const [key, value] of Object.entries(borderRadius)) {
    lines.push(`  --radius-${key}: ${value}px;`);
  }

  lines.push('');

  // Elevation
  lines.push('  /* Elevation */');
  for (const [key, value] of Object.entries(elevation)) {
    lines.push(`  --elevation-${toKebabCase(key)}: ${value}px;`);
  }

  lines.push('');

  // Animation durations
  lines.push('  /* Animation Durations */');
  for (const [key, value] of Object.entries(duration)) {
    lines.push(`  --duration-${toKebabCase(key)}: ${value}ms;`);
  }

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

const outputPath = resolve(dirname(new URL(import.meta.url).pathname), '../src/theme/portal.css');
const css = generateCssTokens();
mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, css, 'utf-8');
console.log(`CSS tokens written to ${outputPath}`);
