export type Species = 'DOG' | 'CAT' | 'BIRD' | 'RABBIT' | 'FISH' | 'REPTILE' | 'OTHER';

export const SPECIES_LIST: ReadonlyArray<{ value: Species; label: string }> = [
  { value: 'DOG', label: 'Dog' },
  { value: 'CAT', label: 'Cat' },
  { value: 'BIRD', label: 'Bird' },
  { value: 'RABBIT', label: 'Rabbit' },
  { value: 'FISH', label: 'Fish' },
  { value: 'REPTILE', label: 'Reptile' },
  { value: 'OTHER', label: 'Other' },
] as const;

export const SPECIES_VALUES = SPECIES_LIST.map((s) => s.value);

export const BREEDS: Record<Species, readonly string[]> = {
  DOG: [
    '', // No breed / Mixed
    'Indie (Desi)',
    'Labrador Retriever',
    'German Shepherd',
    'Golden Retriever',
    'Pug',
    'Beagle',
    'Rottweiler',
    'Doberman',
    'Shih Tzu',
    'Pomeranian',
    'Cocker Spaniel',
    'Dalmatian',
    'Great Dane',
    'Boxer',
    'Siberian Husky',
    'Lhasa Apso',
    'French Bulldog',
    'Bulldog',
    'Dachshund',
    'Chihuahua',
    'Saint Bernard',
    'Mastiff',
    'Rajapalayam',
    'Mudhol Hound',
    'Chippiparai',
    'Kanni',
    'Kombai',
    'Bully Kutta',
    'Rampur Greyhound',
    'Yorkshire Terrier',
    'Maltese',
    'Pitbull',
    'Border Collie',
    'Poodle',
    'Cavalier King Charles Spaniel',
    'Miniature Schnauzer',
    'Cane Corso',
    'Akita',
    'Samoyed',
    'Bernese Mountain Dog',
  ],
  CAT: [
    '',
    'Indie (Desi)',
    'Persian',
    'Siamese',
    'Maine Coon',
    'British Shorthair',
    'Bengal',
    'Ragdoll',
    'Abyssinian',
    'Sphynx',
    'Scottish Fold',
    'Russian Blue',
    'Himalayan',
    'Birman',
    'American Shorthair',
    'Turkish Angora',
  ],
  BIRD: [
    '',
    'Budgerigar (Budgie)',
    'Cockatiel',
    'Indian Ringneck Parakeet',
    'Lovebird',
    'Cockatoo',
    'African Grey',
    'Macaw',
    'Canary',
    'Finch',
    'Conure',
  ],
  RABBIT: [
    '',
    'Holland Lop',
    'Mini Rex',
    'Netherland Dwarf',
    'Lionhead',
    'Flemish Giant',
    'Dutch',
    'English Angora',
    'Mini Lop',
  ],
  FISH: [
    '',
    'Goldfish',
    'Betta',
    'Guppy',
    'Angelfish',
    'Oscar',
    'Discus',
    'Koi',
    'Arowana',
  ],
  REPTILE: [
    '',
    'Red-eared Slider Turtle',
    'Indian Star Tortoise',
    'Leopard Gecko',
    'Bearded Dragon',
    'Ball Python',
    'Chameleon',
    'Iguana',
  ],
  OTHER: [''],
} as const;

export const SPECIES_ICONS: Record<Species, string> = {
  DOG: 'dog',
  CAT: 'cat',
  BIRD: 'bird',
  RABBIT: 'rabbit',
  FISH: 'fish',
  REPTILE: 'turtle',
  OTHER: 'paw',
} as const;
