import type { PrismaClient } from '@prisma/client';
import type { WantListItem } from '@breeyo/types';
import type { ParLevelAlertService } from './par-level-alert.service.js';

const WANT_LIST_SEPARATOR = '──────────────────────────────';

export class WantListService {
  constructor(
    private readonly parLevelAlertService: ParLevelAlertService,
    private readonly prisma: PrismaClient,
  ) {}

  /**
   * D-06/D-24: every item below its par level, with the shortfall
   * (deficit = parLevel - currentStock) attached, biggest shortfalls first
   * so the vet tackles the most urgent reorders first.
   */
  async getWantList(clinicId: string): Promise<WantListItem[]> {
    const lowStockItems = await this.parLevelAlertService.getLowStockItems(clinicId);

    return lowStockItems
      .map((item) => ({ ...item, deficit: item.parLevel - item.currentStock }))
      .sort((a, b) => b.deficit - a.deficit);
  }

  /**
   * D-28: plain-text want-list formatted for a WhatsApp share intent.
   * Date is formatted DD MMM YYYY in IST, matching the repo's existing
   * IST-formatting convention (queue.repository.ts's getTodayIST) rather
   * than pulling in date-fns, which isn't a dependency of @breeyo/api.
   */
  generateWhatsAppText(items: WantListItem[], clinicName: string): string {
    const dateStr = new Date().toLocaleDateString('en-GB', {
      timeZone: 'Asia/Kolkata',
      day: '2-digit',
      month: 'short',
      year: 'numeric',
    });

    const lines = [
      `Breeyo Want-List (${dateStr})`,
      clinicName,
      WANT_LIST_SEPARATOR,
      ...items.map((item, index) => `${index + 1}. ${item.name} - Current: ${item.currentStock}, Par: ${item.parLevel}`),
      WANT_LIST_SEPARATOR,
      'Generated by Breeyo',
    ];

    return lines.join('\n');
  }

  /**
   * Convenience wrapper for the /want-list/text route: resolves the want
   * list and this clinic's name, then formats the WhatsApp text in one call.
   */
  async getWantListWhatsAppText(clinicId: string): Promise<string> {
    const [items, clinic] = await Promise.all([
      this.getWantList(clinicId),
      this.prisma.clinic.findUnique({ where: { id: clinicId }, select: { name: true } }),
    ]);

    return this.generateWhatsAppText(items, clinic?.name ?? 'Clinic');
  }
}
