import { vi } from 'vitest';

const reactMock = {
  createElement: vi.fn(),
  forwardRef: vi.fn((fn: any) => fn),
  memo: vi.fn((fn: any) => fn),
  useState: vi.fn((init: any) => [init, vi.fn()]),
  useCallback: vi.fn((fn: any) => fn),
  useMemo: vi.fn((fn: any) => fn()),
  useRef: vi.fn((init: any) => ({ current: init })),
  useEffect: vi.fn(),
};

// `import React from 'react'; React.createElement(...)` needs a default
// export on the mock, not just named exports — components that only test
// exported constants never hit this path, but ones that invoke the
// component function itself (e.g. BottomSheet's Keyboard-dismiss test) do.
vi.mock('react', () => ({ ...reactMock, default: reactMock }));

vi.mock('react-native', () => ({
  Platform: { OS: 'android', select: vi.fn((obj: any) => obj.android) },
  StyleSheet: { create: (styles: any) => styles },
  Dimensions: {
    get: () => ({ width: 375, height: 812, scale: 2, fontScale: 1 }),
  },
  View: 'View',
  Text: 'Text',
  Image: 'Image',
  TouchableOpacity: 'TouchableOpacity',
  Animated: {
    View: 'Animated.View',
    Text: 'Animated.Text',
    Value: vi.fn(() => ({
      interpolate: vi.fn(),
      setValue: vi.fn(),
    })),
    timing: vi.fn(() => ({ start: vi.fn() })),
    spring: vi.fn(() => ({ start: vi.fn() })),
  },
  Pressable: 'Pressable',
  TextInput: 'TextInput',
  Keyboard: { dismiss: vi.fn() },
}));

const mockComponent = vi.fn(() => null);

vi.mock('react-native-paper', () => ({
  MD3LightTheme: {
    dark: false,
    roundness: 4,
    version: 3,
    isV3: true,
    colors: {
      primary: '#6750A4',
      onPrimary: '#FFFFFF',
      primaryContainer: '#EADDFF',
      onPrimaryContainer: '#21005D',
      secondary: '#625B71',
      onSecondary: '#FFFFFF',
      secondaryContainer: '#E8DEF8',
      onSecondaryContainer: '#1D192B',
      tertiary: '#7D5260',
      onTertiary: '#FFFFFF',
      tertiaryContainer: '#FFD8E4',
      onTertiaryContainer: '#31111D',
      error: '#B3261E',
      onError: '#FFFFFF',
      errorContainer: '#F9DEDC',
      onErrorContainer: '#410E0B',
      background: '#FFFBFE',
      onBackground: '#1C1B1F',
      surface: '#FFFBFE',
      onSurface: '#1C1B1F',
      surfaceVariant: '#E7E0EC',
      onSurfaceVariant: '#49454F',
      outline: '#79747E',
      outlineVariant: '#CAC4D0',
      elevation: {
        level0: 'transparent',
        level1: '#F7F2FA',
        level2: '#F3EDF7',
        level3: '#EFE9F4',
        level4: '#ECE6F0',
        level5: '#E8E0EB',
      },
      surfaceDisabled: 'rgba(28, 27, 31, 0.12)',
      onSurfaceDisabled: 'rgba(28, 27, 31, 0.38)',
      backdrop: 'rgba(50, 47, 55, 0.4)',
      inverseSurface: '#313033',
      inverseOnSurface: '#F4EFF4',
      inversePrimary: '#D0BCFF',
      shadow: '#000000',
      scrim: '#000000',
    },
    fonts: {
      displayLarge: {
        fontFamily: 'System',
        fontSize: 57,
        fontWeight: '400',
        lineHeight: 64,
        letterSpacing: -0.25,
      },
      displayMedium: {
        fontFamily: 'System',
        fontSize: 45,
        fontWeight: '400',
        lineHeight: 52,
        letterSpacing: 0,
      },
      displaySmall: {
        fontFamily: 'System',
        fontSize: 36,
        fontWeight: '400',
        lineHeight: 44,
        letterSpacing: 0,
      },
      headlineLarge: {
        fontFamily: 'System',
        fontSize: 32,
        fontWeight: '400',
        lineHeight: 40,
        letterSpacing: 0,
      },
      headlineMedium: {
        fontFamily: 'System',
        fontSize: 28,
        fontWeight: '400',
        lineHeight: 36,
        letterSpacing: 0,
      },
      headlineSmall: {
        fontFamily: 'System',
        fontSize: 24,
        fontWeight: '400',
        lineHeight: 32,
        letterSpacing: 0,
      },
      titleLarge: {
        fontFamily: 'System',
        fontSize: 22,
        fontWeight: '400',
        lineHeight: 28,
        letterSpacing: 0,
      },
      titleMedium: {
        fontFamily: 'System',
        fontSize: 16,
        fontWeight: '500',
        lineHeight: 24,
        letterSpacing: 0.15,
      },
      titleSmall: {
        fontFamily: 'System',
        fontSize: 14,
        fontWeight: '500',
        lineHeight: 20,
        letterSpacing: 0.1,
      },
      bodyLarge: {
        fontFamily: 'System',
        fontSize: 16,
        fontWeight: '400',
        lineHeight: 24,
        letterSpacing: 0.5,
      },
      bodyMedium: {
        fontFamily: 'System',
        fontSize: 14,
        fontWeight: '400',
        lineHeight: 20,
        letterSpacing: 0.25,
      },
      bodySmall: {
        fontFamily: 'System',
        fontSize: 12,
        fontWeight: '400',
        lineHeight: 16,
        letterSpacing: 0.4,
      },
      labelLarge: {
        fontFamily: 'System',
        fontSize: 14,
        fontWeight: '500',
        lineHeight: 20,
        letterSpacing: 0.1,
      },
      labelMedium: {
        fontFamily: 'System',
        fontSize: 12,
        fontWeight: '500',
        lineHeight: 16,
        letterSpacing: 0.5,
      },
      labelSmall: {
        fontFamily: 'System',
        fontSize: 11,
        fontWeight: '500',
        lineHeight: 16,
        letterSpacing: 0.5,
      },
    },
    animation: { scale: 1, defaultAnimationDuration: 200 },
  },
  useTheme: vi.fn(),
  // Component mocks
  Text: mockComponent,
  Button: mockComponent,
  TextInput: Object.assign(mockComponent, {
    Icon: mockComponent,
    Affix: mockComponent,
  }),
  HelperText: mockComponent,
  Chip: mockComponent,
  IconButton: mockComponent,
  Divider: mockComponent,
  ProgressBar: mockComponent,
  ActivityIndicator: mockComponent,
  Searchbar: mockComponent,
  Snackbar: mockComponent,
  Avatar: {
    Image: mockComponent,
    Text: mockComponent,
    Icon: mockComponent,
  },
  List: {
    Item: mockComponent,
    Icon: mockComponent,
    Accordion: mockComponent,
  },
}));
